# Generated by Django 4.1.7 on 2023-02-19 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PermanenceDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("call_amount_1", models.PositiveSmallIntegerField(null=True)),
                ("call_amount_2", models.PositiveSmallIntegerField(null=True)),
                ("call_amount_3", models.PositiveSmallIntegerField(null=True)),
                ("call_amount_4", models.PositiveSmallIntegerField(null=True)),
                ("call_duration_1", models.PositiveSmallIntegerField(null=True)),
                ("call_duration_2", models.PositiveSmallIntegerField(null=True)),
                ("call_duration_3", models.PositiveSmallIntegerField(null=True)),
                ("call_duration_4", models.PositiveSmallIntegerField(null=True)),
                (
                    "inscrite_1",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inscrite_2",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inscrite_3",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inscrite_4",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
